// To store the pattern of colours generated by the game and the pattern of colours clicked by the user
let buttonColours = ["red", "blue", "green", "yellow"];
let gamePattern = [];
let level = 0;
// To generate a random colour and add it to the game pattern
function nextSequence() {
  level++;
  $("#level-title").text("Level " + level);
  let randomNumber = Math.floor(Math.random() * 4);
  let randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);
  // To animate the button and play the sound for the randomly chosen colour
  $("#" + randomChosenColour).fadeIn(100).fadeOut(100).fadeIn(100);
  let audio = new Audio("sounds/" + randomChosenColour + ".mp3");
  audio.play();
}
// To store the pattern of colours clicked by the user
let userClickedPattern = [];
// To detect when a button is clicked and store the id of the button in the user pattern array, play the sound for the button and animate it
$(".btn").click(function() {
  let userChosenColour = $(this).attr("id");
  userClickedPattern.push(userChosenColour);
  playSound(userChosenColour);
  animatePress(userChosenColour);
});
//2. Create a new function called playSound() that takes a single input parameter called name.
function playSound(name) {
  let audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}
//Add Animations to User Clicks
function animatePress(currentColour) {
  $("#" + currentColour).addClass("pressed");
  setTimeout(function() {
    $("#" + currentColour).removeClass("pressed");
  }, 100);
}
let started = false;

$(document).keypress(function() {
  if (!started) {
    nextSequence();
    started = true;
  }
});

function checkAnswer(currentLevel) {

    if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {

      console.log("success");

      if (userClickedPattern.length === gamePattern.length){
        setTimeout(function () {
          nextSequence();
        }, 1000);
      }

    } else {

      console.log("wrong");

      //1. In the sounds folder, there is a sound called wrong.mp3, play this sound if the user got one of the answers wrong.
      playSound("wrong");

      //2. In the styles.css file, there is a class called "game-over", apply this class to the body of the website when the user gets one of the answers wrong and then remove it after 200 milliseconds.
      $("body").addClass("game-over");
      setTimeout(function () {
        $("body").removeClass("game-over");
      }, 200);

      //3. Change the h1 title to say "Game Over, Press Any Key to Restart" if the user got the answer wrong.
      $("#level-title").text("Game Over, Press Any Key to Restart");
    }

}
function startOver() {
  level = 0;
  gamePattern = [];
  started = false;
}
